FROM mcr.microsoft.com/windows/servercore/insider:10.0.18922.1000
LABEL maintainer="https://github.com/OvrAp3x/DSCStack/"
COPY [ "Modules", "C:/Program Files/WindowsPowerShell/Modules/" ]
COPY [ "Docker.ps1", "./Docker.ps1" ]
COPY [ "sqlncli.msi", "./sqlncli.msi" ]
COPY [ "DockerMon.ps1", "./DockerMon.ps1" ]
RUN powershell.exe -Command .\Docker.ps1; rm .\Docker.ps1,.\sqlncli.msi
EXPOSE 8080
CMD ["powershell.exe", "c:\\DockerMon.ps1"]
